---
- hosts: all
  user: ansible
  become: true
  tasks:
    - name: Adding glo-ar-{{ansible_hostname}} to AllowGroups in SSHD
      replace:
             dest: /etc/ssh/sshd_config
             regexp: 'glo-ar-iahdvltplc006'
             replace: 'glo-ar-{{ansible_hostname}}'
             backup: yes

    - name: Creating new LVM Volume Group
      lvg:
             vg: vg01
             pvs: /dev/sdb
             state: present
    - name: Creating new LVM Logical Volume
      lvol:
             vg: vg01
             lv: lvlocal
             size: 100%FREE

    - name: Creating a xfs filesystem for local disk
      filesystem:
             fstype: ext4
             dev: /dev/mapper/vg01-lvlocal

    - name: Creating local directory
      file:
             path: /local
             state: directory
             mode: 0755

    - name: Mounting local disk
      mount:
             path: /local
             src: /dev/mapper/vg01-lvlocal
             fstype: ext4
             state: present
    
    - name: Registering server to spacewalk
      rhn_register:
             state: present
             activationkey: 1-03iahd-cent06-vm-key
             server_url: http://spacewalk.logistics.corp/XMLRPC
             sslcacert: /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT
             username: casill-adm
             password: marjie1453
            
    - name: Install package software
      yum: 
             name: python2-pip
             state: latest
                        
    - name:  Upgrading python-pip
      shell: /bin/bash -c "pip install --upgrade pip"

    - name: Installing pexpect
      shell: /bin/bash -c "pip install pexpect"    

    - name: Updating all packages
      yum:
             name: '*'
             state: latest
             
    - name: PBIS registration
      expect: 
             command: /bin/bash -c "/opt/pbis/bin/domainjoin-cli join logistics.corp casill-adm"
             responses: 
                    Password*: "r00t@2015"
                    
    - name: Restarting PBIS service
      shell:  /bin/bash -c "/opt/pbis/bin/config DomainManagerIgnoreAllTrusts true; service lwsmd restart; sleep 5"

    - name: Configuring PBIS DomainPrefix
      shell: /bin/bash -c "/opt/pbis/bin/config UserDomainPrefix LOGISTICS; /opt/pbis/bin/config AssumeDefaultDomain true; /opt/pbis/bin/config LoginShellTemplate /bin/bash"    
